"""Self-hosted ZenPlus browser RUM SDK.

This intentionally ships as one dependency-free classic script so monitored
applications never rely on a CDN.  The Web Vitals algorithms follow the public
metric definitions: CLS session windows (1 s gap / 5 s maximum), LCP's last
eligible candidate, and INP's high-percentile interaction latency.
"""

RUM_SDK_VERSION = "2.0.0"

RUM_SDK = r'''(function(){
  "use strict";
  if(window.ZenPlusRUM&&window.ZenPlusRUM.__loaded)return;
  var script=document.currentScript||{},d=script.dataset||{};
  var key=d.key||"",app=d.app||location.hostname,service=d.service||app;
  if(!key){console.warn("ZenPlus RUM: data-key is required");return;}
  var SDK_VERSION="2.0.0",originalFetch=window.fetch&&window.fetch.bind(window);
  var endpoint=new URL("/api/v1/apm/rum/ingest",script.src||location.href);endpoint.searchParams.set("key",key);endpoint=endpoint.toString();
  function clamp(v,f){v=Number(v);return isFinite(v)&&v>=0&&v<=1?v:f;}
  var sampleRate=clamp(d.sampleRate,1),replaySampleRate=clamp(d.replaySampleRate,0);
  var trackActions=d.trackActions!=="false",trackLongTasks=d.trackLongTasks!=="false";
  var consent=d.consent!=="pending"&&navigator.doNotTrack!=="1",consentEpoch=0,privacy=d.privacy||"mask-user-input";
  var context={},userId="",queue=[],inflight=[],retryBatchLength=0,timer=0,retry=1000,flushing=false,dropped=0;
  var MAX_BATCH_EVENTS=50,MAX_BATCH_BYTES=256*1024,MAX_UNLOAD_BYTES=60*1024,MAX_QUEUE_EVENTS=250;
  function hex(n){var a=new Uint8Array(n);crypto.getRandomValues(a);return Array.from(a,function(x){return x.toString(16).padStart(2,"0")}).join("");}
  function randomId(){return typeof crypto.randomUUID==="function"?crypto.randomUUID():hex(16);}
  function hash(s){var h=2166136261;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
  function scrub(s,n){return String(s==null?"":s).replace(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g,"[email]").replace(/(password|passwd|secret|token|api[_-]?key)\s*[:=]\s*[^\s,;&]+/ig,"$1=[redacted]").slice(0,n||1024);}
  function safePathPart(p){var decoded=p;try{decoded=decodeURIComponent(p);}catch(e){}return /^(?:\d+|[a-f\d]{16,}|[a-f\d]{8}-(?:[a-f\d]{4}-){3}[a-f\d]{12})$/i.test(decoded)||decoded.indexOf("@")>=0?":id":p;}
  function safeUrl(value){try{var u=new URL(value,location.href);u.username="";u.password="";u.search="";u.hash="";u.pathname=u.pathname.split("/").map(safePathPart).join("/");return u.toString();}catch(e){return "";}}
  function currentViewName(){var name=location.pathname||"/",route=String(location.hash||"");if(route.indexOf("#/")===0)name=route.slice(1).split(/[?#]/)[0]||"/";return scrub(name.split("/").map(safePathPart).join("/"),512);}
  function selector(el){if(!el||el.nodeType!==1)return "";var out=el.tagName.toLowerCase(),c=privacy==="strict"?[]:String(el.className||"").trim().split(/\s+/).filter(Boolean).slice(0,2);if(c.length)out+="."+c.map(function(x){return x.replace(/[^\w-]/g,"");}).join(".");var role=el.getAttribute&&el.getAttribute("role");if(role)out+='[role="'+scrub(role,40)+'"]';return out.slice(0,256);}
  function storageGet(k){try{return sessionStorage.getItem(k);}catch(e){return null;}}
  function storageSet(k,v){try{sessionStorage.setItem(k,v);}catch(e){}}
  function byteSize(value){try{return new TextEncoder().encode(value).byteLength;}catch(e){return unescape(encodeURIComponent(value)).length;}}
  function batchBody(batch){return JSON.stringify({events:batch});}
  var namespace=endpoint+"|"+key+"|"+app,sk="zp_rum_"+hash(namespace).toString(16)+"_";
  var sid=storageGet(sk+"sid"),last=Number(storageGet(sk+"last")||0),now=Date.now();
  if(!sid||now-last>1800000)sid=randomId();last=now;storageSet(sk+"sid",sid);storageSet(sk+"last",String(last));
  function isSampled(id){return (hash(app+":"+id)/4294967296)<sampleRate;}
  var sampled=isSampled(sid);
  function ensureSession(touch){var t=Date.now(),rotated=!!touch&&(!sid||t-last>1800000);if(rotated){sid=randomId();sampled=isSampled(sid);storageSet(sk+"sid",sid);if(typeof view!=="undefined"&&view){view.finalized=true;if(typeof lcpObserver!=="undefined"&&lcpObserver){lcpObserver.disconnect();lcpObserver=null;}view={id:randomId(),name:currentViewName(),started:performance.now(),finalized:false,hard:false,vitals:{},attribution:{}};resetVitals();}}if(rotated||touch){last=t;storageSet(sk+"last",String(last));}return rotated;}
  function base(type){return {client_token:key,event_id:randomId(),application_id:app,service_name:service,service_version:d.version||"",sdk_version:SDK_VERSION,event_type:type,timestamp_ms:Date.now(),session_id:sid,view_id:view.id,view_name:view.name,url:safeUrl(location.href),user_id:privacy==="strict"?"":userId,sample_rate:sampleRate,sampled:sampled,attributes:privacy==="strict"?{}:Object.assign({},context)};}
  function persist(){try{storageSet(sk+"queue",JSON.stringify(queue.slice(-MAX_QUEUE_EVENTS)));storageSet(sk+"inflight",JSON.stringify(inflight.slice(-MAX_BATCH_EVENTS)));storageSet(sk+"retry_length",String(inflight.length||retryBatchLength));}catch(e){}}
  function restore(){try{var q=JSON.parse(storageGet(sk+"queue")||"[]"),pending=JSON.parse(storageGet(sk+"inflight")||"[]"),savedLength=Number(storageGet(sk+"retry_length")||0);if(!Array.isArray(q))q=[];if(!Array.isArray(pending))pending=[];queue=pending.concat(q).slice(0,MAX_QUEUE_EVENTS);retryBatchLength=Math.min(queue.length,pending.length||savedLength||0);inflight=[];}catch(e){queue=[];inflight=[];retryBatchLength=0;}}
  function enqueue(type,extra,force){if(!consent)return;var isCheckpoint=type==="view"&&extra&&extra.end_reason==="checkpoint",rotated=ensureSession(!isCheckpoint),isFinal=type==="view"&&extra&&extra.is_final===true,isViewStart=type==="view"&&extra&&extra.end_reason==="view_start";if(rotated&&isFinal){view.finalized=true;persist();return;}if(!sampled&&!force)return;if(rotated&&sampled&&!isViewStart)queue.push(Object.assign(base("view"),{is_final:false,end_reason:"view_start"}));var p=Object.assign(base(type),extra||{});if(dropped){p.attributes=Object.assign({},p.attributes,{"sdk.dropped_events":String(dropped)});dropped=0;}queue.push(p);while(inflight.length+queue.length>MAX_QUEUE_EVENTS){queue.pop();dropped++;}persist();if(queue.length>=20)flush(false);else schedule(2000);}
  function schedule(ms){if(timer)return;timer=setTimeout(function(){timer=0;flush(false);},ms);}
  function takeBatch(limit){var batch=[],deferred=[],maxEvents=retryBatchLength||MAX_BATCH_EVENTS;if(retryBatchLength&&byteSize(batchBody(queue.slice(0,retryBatchLength)))>=limit)return batch;while(queue.length&&batch.length<maxEvents){var event=queue.shift(),singleBytes=byteSize(batchBody([event]));if(singleBytes>=MAX_BATCH_BYTES){dropped++;continue;}var candidate=batch.concat([event]);if(byteSize(batchBody(candidate))<limit)batch=candidate;else deferred.push(event);}queue=deferred.concat(queue);if(batch.length)retryBatchLength=0;return batch;}
  function peekBatch(limit){var batch=[],maxEvents=retryBatchLength||MAX_BATCH_EVENTS;for(var i=0;i<queue.length&&batch.length<maxEvents;i++){var candidate=batch.concat([queue[i]]);if(byteSize(batchBody(candidate))<limit)batch=candidate;}if(retryBatchLength&&batch.length<retryBatchLength)return [];return batch;}
  function removeQueued(events){var ids=Object.create(null),retryIds=Object.create(null);events.forEach(function(e){ids[e.event_id]=true;});queue.slice(0,retryBatchLength).forEach(function(e){retryIds[e.event_id]=true;});queue=queue.filter(function(e){return !ids[e.event_id];});if(retryBatchLength)retryBatchLength=queue.reduce(function(n,e){return n+(retryIds[e.event_id]?1:0);},0);}
  function intakeError(status,retryable,events){var err=new Error("RUM intake "+status);err.__zpIntake=true;err.retryable=retryable;err.events=events;return err;}
  function postBatch(batch,unloading){var body=batchBody(batch);return Promise.resolve().then(function(){return originalFetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:body,keepalive:!!unloading,credentials:"omit",cache:"no-store"});}).then(function(r){if(r.ok)return;if(r.status===413){if(batch.length===1)throw intakeError(413,false,batch);var middle=Math.ceil(batch.length/2),parts=[batch.slice(0,middle),batch.slice(middle)];return Promise.all(parts.map(function(part){return postBatch(part,unloading).then(function(){return null;},function(e){return e;});})).then(function(results){var retryEvents=[],terminalEvents=[];results.forEach(function(e){if(!e)return;if(e.retryable===true)retryEvents=retryEvents.concat(e.events||[]);else terminalEvents=terminalEvents.concat(e.events||[]);terminalEvents=terminalEvents.concat(e.terminalEvents||[]);});if(retryEvents.length){var combined=intakeError(413,true,retryEvents);combined.terminalEvents=terminalEvents;throw combined;}if(terminalEvents.length)throw intakeError(413,false,terminalEvents);});}throw intakeError(r.status,r.status===408||r.status===429||r.status>=500,batch);}).catch(function(e){if(e&&e.__zpIntake)throw e;throw intakeError("network",true,batch);});}
  function sendUnloadTail(){var batch=peekBatch(MAX_UNLOAD_BYTES),epoch=consentEpoch;if(!batch.length)return;postBatch(batch,true).then(function(){if(epoch===consentEpoch){removeQueued(batch);persist();}}).catch(function(e){if(epoch!==consentEpoch||!consent)return;var terminal=e&&Array.isArray(e.terminalEvents)?e.terminalEvents:[];if(e&&e.retryable===false)terminal=terminal.concat(e.events||batch);if(terminal.length){removeQueued(terminal);dropped+=terminal.length;persist();}});}
  function flush(unloading){if(!queue.length||!originalFetch||!consent)return;if(flushing){if(unloading)sendUnloadTail();persist();return;}var batch=takeBatch(unloading?MAX_UNLOAD_BYTES:MAX_BATCH_BYTES);if(!batch.length){persist();return;}var epoch=consentEpoch;flushing=true;inflight=batch.slice();persist();postBatch(batch,unloading).then(function(){inflight=[];retryBatchLength=0;persist();retry=1000;}).catch(function(e){var failed=e&&Array.isArray(e.events)?e.events:batch,terminal=e&&Array.isArray(e.terminalEvents)?e.terminalEvents:[];inflight=[];if(epoch!==consentEpoch||!consent){retryBatchLength=0;persist();return;}dropped+=terminal.length;if(e&&e.retryable===true){var merged=failed.concat(queue);if(merged.length>MAX_QUEUE_EVENTS)dropped+=merged.length-MAX_QUEUE_EVENTS;queue=merged.slice(0,MAX_QUEUE_EVENTS);retryBatchLength=Math.min(failed.length,queue.length);persist();if(!unloading){schedule(retry);retry=Math.min(retry*2,30000);}}else{retryBatchLength=0;dropped+=failed.length;persist();}}).finally(function(){flushing=false;if(queue.length&&!unloading&&consent)schedule(2000);});}
  restore();

  var view={id:randomId(),name:currentViewName(),started:performance.now(),finalized:false,hard:true,vitals:{},attribution:{}};
  function resetVitals(){view.vitals={};view.attribution={};clsValue=0,clsWindow=0,clsStart=0,clsLast=0,inpInteractions=new Map(),minInteractionId=Infinity,maxInteractionId=0,interactionBase=Number(performance.interactionCount||0),lcpEntry=null;if(view.hard)readNavigation();}
  function emitViewStart(){enqueue("view",{is_final:false,end_reason:"view_start"});}
  function finalizeView(reason){if(view.finalized)return;view.finalized=true;readNavigation();var v=view.vitals,a={};Object.keys(v).forEach(function(k){if(v[k]!=null&&isFinite(v[k]))a[k]=Math.max(0,v[k]);});enqueue("view",Object.assign(a,{is_final:true,end_reason:reason||"route_change",duration_ms:Math.max(0,performance.now()-view.started),vital_attribution:Object.assign({},view.attribution)}));flush(reason==="pagehide"||reason==="hidden");}
  function startView(name){finalizeView("route_change");view={id:randomId(),name:scrub(name||currentViewName(),512),started:performance.now(),finalized:false,hard:false,vitals:{},attribution:{}};resetVitals();emitViewStart();}
  function routeChanged(){var n=currentViewName();if(n!==view.name)startView(n);}

  var clsValue=0,clsWindow=0,clsStart=0,clsLast=0,clsSupported=false,inpInteractions=new Map(),minInteractionId=Infinity,maxInteractionId=0,interactionBase=Number(performance.interactionCount||0),lcpEntry=null;
  function interactionCount(){var nativeCount=Number(performance.interactionCount||0),nativeDelta=Math.max(0,nativeCount-interactionBase);if(nativeCount>0)return Math.max(inpInteractions.size,nativeDelta);if(maxInteractionId&&minInteractionId!==Infinity)return Math.max(inpInteractions.size,Math.floor((maxInteractionId-minInteractionId)/7)+1);return inpInteractions.size;}
  function inpRank(length){return Math.min(Math.floor(interactionCount()/50),length-1);}
  function readNavigation(){var nav=view.hard&&performance.getEntriesByType("navigation")[0],fcp=view.hard&&performance.getEntriesByName("first-contentful-paint")[0];if(nav){var activation=nav.activationStart||0;if(nav.responseStart>0)view.vitals.ttfb=Math.max(0,nav.responseStart-activation);if(nav.loadEventEnd>0)view.vitals.load_ms=Math.max(0,nav.loadEventEnd-activation);}if(fcp)view.vitals.fcp=Math.max(0,fcp.startTime-(nav&&nav.activationStart||0));if(view.hard&&lcpEntry)view.vitals.lcp=lcpEntry.startTime;if(clsSupported)view.vitals.cls=clsValue;var durations=Array.from(inpInteractions.values()).map(function(x){return x.duration;}).sort(function(a,b){return b-a;});if(durations.length)view.vitals.inp=durations[inpRank(durations.length)];}
  function observe(type,cb,opts){try{var po=new PerformanceObserver(cb);po.observe(Object.assign({type:type,buffered:true},opts||{}));return po;}catch(e){return null;}}
  var lcpObserver=observe("largest-contentful-paint",function(list){if(!view.hard)return;list.getEntries().forEach(function(e){lcpEntry=e;view.vitals.lcp=e.startTime;view.attribution["lcp.element"]=selector(e.element);view.attribution["lcp.url"]=safeUrl(e.url||"");});});
  function stopLcp(){readNavigation();if(lcpObserver){lcpObserver.disconnect();lcpObserver=null;}}
  addEventListener("keydown",stopLcp,{once:true,capture:true});addEventListener("click",stopLcp,{once:true,capture:true});
  clsSupported=typeof PerformanceObserver!=="undefined"&&PerformanceObserver.supportedEntryTypes&&PerformanceObserver.supportedEntryTypes.indexOf("layout-shift")>=0;
  var clsObserver=clsSupported?observe("layout-shift",function(list){list.getEntries().forEach(function(e){if(e.hadRecentInput)return;if(!clsStart||e.startTime-clsLast>1000||e.startTime-clsStart>5000){clsStart=e.startTime;clsWindow=e.value;}else clsWindow+=e.value;clsLast=e.startTime;if(clsWindow>clsValue){clsValue=clsWindow;view.vitals.cls=clsValue;var src=e.sources&&e.sources[0];view.attribution["cls.element"]=selector(src&&src.node);}});}):null;clsSupported=!!clsObserver;
  observe("event",function(list){list.getEntries().forEach(function(e){if(!e.interactionId)return;minInteractionId=Math.min(minInteractionId,e.interactionId);maxInteractionId=Math.max(maxInteractionId,e.interactionId);var prior=inpInteractions.get(e.interactionId);if(!prior||e.duration>prior.duration)inpInteractions.set(e.interactionId,{duration:e.duration,name:e.name,target:selector(e.target)});});readNavigation();if(inpInteractions.size){var vals=Array.from(inpInteractions.values()).sort(function(a,b){return b.duration-a.duration;}),candidate=vals[inpRank(vals.length)];view.attribution["inp.event_type"]=candidate.name;view.attribution["inp.target"]=candidate.target;}},{durationThreshold:40});
  resetVitals();emitViewStart();

  function traceFrom(value){var m=/^[\da-f]{2}-([\da-f]{32})-([\da-f]{16})-([\da-f]{2})(?:-|$)/i.exec(value||"");return m?m[1].toLowerCase():"";}
  function resource(type,url,method,status,started,trace,failed,extra){var duration=Math.max(0,performance.now()-started);enqueue("resource",Object.assign({resource_url:safeUrl(url),resource_type:type,method:method||"GET",status_code:status||0,duration_ms:duration,backend_trace_id:trace||"",attributes:{failed:failed?"true":"false"}},extra||{}));}
  if(originalFetch){window.fetch=function(input,init){var target;try{target=new URL(input instanceof Request?input.url:String(input),location.href);}catch(e){return originalFetch(input,init);}if(target.toString().indexOf(endpoint.split("?")[0])===0)return originalFetch(input,init);var request,headers;try{request=new Request(input,init);headers=new Headers(request.headers);}catch(e){return originalFetch(input,init);}var tp=headers.get("traceparent"),trace=traceFrom(tp);if(target.origin===location.origin&&!tp){trace=hex(16);headers.set("traceparent","00-"+trace+"-"+hex(8)+"-"+(sampled?"01":"00"));try{request=new Request(request,{headers:headers});}catch(e){return originalFetch(input,init);}}var started=performance.now(),method=request.method||"GET";return originalFetch(request).then(function(r){resource("fetch",target.toString(),method,r.status,started,trace,!r.ok);return r;},function(err){resource("fetch",target.toString(),method,0,started,trace,true,{error_message:scrub(err&&err.message||"Fetch failed",1024)});throw err;});};}
  if(window.XMLHttpRequest){var XO=XMLHttpRequest.prototype.open,XS=XMLHttpRequest.prototype.send,XH=XMLHttpRequest.prototype.setRequestHeader;XMLHttpRequest.prototype.open=function(method,url){this.__zp={method:String(method||"GET").toUpperCase(),url:String(url),headers:{}};return XO.apply(this,arguments);};XMLHttpRequest.prototype.setRequestHeader=function(name,value){if(this.__zp)this.__zp.headers[String(name).toLowerCase()]=String(value);return XH.apply(this,arguments);};XMLHttpRequest.prototype.send=function(){var z=this.__zp,started=performance.now(),trace="";if(z){try{var u=new URL(z.url,location.href),supplied=Object.prototype.hasOwnProperty.call(z.headers,"traceparent");trace=traceFrom(z.headers.traceparent);if(u.origin===location.origin&&!supplied){trace=hex(16);XH.call(this,"traceparent","00-"+trace+"-"+hex(8)+"-"+(sampled?"01":"00"));}this.addEventListener("loadend",function(){resource("xhr",u.toString(),z.method,this.status,started,trace,this.status===0||this.status>=400);},{once:true});}catch(e){}}return XS.apply(this,arguments);};}
  observe("resource",function(list){list.getEntries().forEach(function(e){if(/^(fetch|xmlhttprequest)$/.test(e.initiatorType))return;enqueue("resource",{resource_url:safeUrl(e.name),resource_type:e.initiatorType||"resource",method:"GET",status_code:Number(e.responseStatus||0),duration_ms:e.duration||0,transfer_size:Number(e.transferSize||0),encoded_body_size:Number(e.encodedBodySize||0),attributes:{failed:e.responseStatus>=400?"true":"false"}});});});

  function fingerprint(s){return (hash(String(s))>>>0).toString(16);}
  addEventListener("error",function(e){var t=e.target;if(t&&t!==window&&(t.src||t.href)){enqueue("resource",{resource_url:safeUrl(t.src||t.href),resource_type:(t.tagName||"resource").toLowerCase(),status_code:0,attributes:{failed:"true"}});return;}var err=e.error||{},message=scrub(e.message||err.message||"JavaScript error",4096),stack=scrub(err.stack||"",16384),source=safeUrl(e.filename||"");enqueue("error",{error_message:message,error_type:scrub(err.name||"Error",255),error_stack:stack,error_source:source,error_fingerprint:fingerprint((err.name||"Error")+":"+message+":"+source+":"+(e.lineno||0)),attributes:{line:String(e.lineno||0),column:String(e.colno||0),handled:"false"}},true);},true);
  addEventListener("unhandledrejection",function(e){var r=e.reason||{},message=scrub(r.message||String(r)||"Unhandled rejection",4096),stack=scrub(r.stack||"",16384);enqueue("error",{error_message:message,error_type:scrub(r.name||"UnhandledRejection",255),error_stack:stack,error_fingerprint:fingerprint("promise:"+message),attributes:{handled:"false"}},true);});
  if(trackLongTasks)observe("longtask",function(list){list.getEntries().forEach(function(e){enqueue("long_task",{action_name:"Long task",action_type:"long_task",duration_ms:e.duration||0,target:selector(e.attribution&&e.attribution[0]&&e.attribution[0].containerElement)});});});
  var recentClicks=[];
  if(trackActions)addEventListener("click",function(e){var target=selector(e.target),now=Date.now(),x=e.clientX||0,y=e.clientY||0;enqueue("action",{action_name:"Click "+(target||"element"),action_type:"click",target:target});recentClicks=recentClicks.filter(function(c){return now-c.t<1000&&Math.abs(c.x-x)<50&&Math.abs(c.y-y)<50&&c.target===target;});recentClicks.push({t:now,x:x,y:y,target:target});if(recentClicks.length>=3){enqueue("action",{action_name:"Rage click",action_type:"rage_click",target:target});recentClicks=[];}},true);
  ["pushState","replaceState"].forEach(function(name){var fn=history[name];if(!fn)return;history[name]=function(){var result=fn.apply(this,arguments);setTimeout(routeChanged,0);return result;};});
  addEventListener("popstate",routeChanged);addEventListener("hashchange",routeChanged);
  addEventListener("pagehide",function(){finalizeView("pagehide");flush(true);});
  addEventListener("pageshow",function(e){if(e.persisted)startView(currentViewName());});
  addEventListener("visibilitychange",function(){if(document.visibilityState==="hidden"){stopLcp();finalizeView("hidden");flush(true);}else if(document.visibilityState==="visible"){setTimeout(function(){if(view.finalized)startView(currentViewName());},0);}});
  addEventListener("online",function(){flush(false);});
  setInterval(function(){if(consent&&queue.length)flush(false);},10000);
  setInterval(function(){if(consent&&!view.finalized&&Date.now()-last<=1800000){readNavigation();var v=Object.assign({},view.vitals);enqueue("view",Object.assign(v,{is_final:false,end_reason:"checkpoint",duration_ms:Math.max(0,performance.now()-view.started),vital_attribution:Object.assign({},view.attribution)}));}},60000);

  window.ZenPlusRUM={__loaded:true,version:SDK_VERSION,capabilities:{sessionReplay:false,sessionReplayReason:"capture and storage are not enabled in this release",sourceMaps:false},grantConsent:function(){consent=true;flush(false);},setConsent:function(v){var next=v==="granted"||v===true;if(!next){consentEpoch++;queue=[];inflight=[];retryBatchLength=0;}consent=next;persist();if(consent)flush(false);},setUser:function(u){if(privacy==="strict")return;var raw="";if(u&&typeof u==="object"){if(u.id)raw=String(u.id);else if(u.email)raw="email_"+hash(String(u.email)).toString(16);}else raw=String(u||"");if(raw.indexOf("@")>=0)raw="email_"+hash(raw).toString(16);userId=scrub(raw,255);},setContext:function(v){if(privacy==="strict"||!v||typeof v!=="object")return;Object.keys(v).forEach(function(k){var name=String(k).slice(0,128);if(!Object.prototype.hasOwnProperty.call(context,name)&&Object.keys(context).length>=32)return;if(!/(password|secret|token|cookie|authorization)/i.test(name))context[name]=scrub(v[k],1024);});},addAction:function(name,attrs){var custom={};if(privacy!=="strict"&&attrs&&typeof attrs==="object")Object.keys(attrs).slice(0,Math.max(0,32-Object.keys(context).length)).forEach(function(k){if(!/(password|secret|token|cookie|authorization)/i.test(k))custom[String(k).slice(0,128)]=scrub(attrs[k],1024);});enqueue("action",{action_name:scrub(name,512),action_type:"custom",attributes:privacy==="strict"?{}:Object.assign({},context,custom)});},startView:startView,getConfiguration:function(){return {applicationId:app,service:service,version:d.version||"",sampleRate:sampleRate,replaySampleRate:replaySampleRate,privacy:privacy,sessionReplayEnabled:false};},flush:function(){flush(false);}};
})();'''
