CREATE TABLE IF NOT EXISTS zenplus.ping_metrics (device_id UUID, timestamp DateTime64(3, 'UTC'), is_up UInt8, rtt_ms Float64, packet_loss Float32, jitter_ms Float64, min_rtt_ms Float64, max_rtt_ms Float64, packets_sent UInt16, packets_recv UInt16, poller_id String, ip_address IPv4) ENGINE = MergeTree() PARTITION BY toYYYYMM(timestamp) ORDER BY (device_id, timestamp) TTL toDateTime(timestamp) + INTERVAL 30 DAY DELETE SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS zenplus.ping_metrics_1h (device_id UUID, timestamp DateTime64(3, 'UTC'), avg_rtt_ms Float64, min_rtt_ms Float64, max_rtt_ms Float64, p95_rtt_ms Float64, avg_packet_loss Float32, avg_jitter_ms Float64, uptime_pct Float32, sample_count UInt32, ip_address IPv4) ENGINE = MergeTree() PARTITION BY toYYYYMM(timestamp) ORDER BY (device_id, timestamp) TTL toDateTime(timestamp) + INTERVAL 365 DAY DELETE;

CREATE TABLE IF NOT EXISTS zenplus.device_status_log (device_id UUID, timestamp DateTime64(3, 'UTC'), old_status String, new_status String, reason String, duration_sec UInt64) ENGINE = MergeTree() PARTITION BY toYYYYMM(timestamp) ORDER BY (device_id, timestamp) TTL toDateTime(timestamp) + INTERVAL 365 DAY DELETE;

CREATE MATERIALIZED VIEW IF NOT EXISTS zenplus.ping_metrics_5m_mv TO zenplus.ping_metrics_5m AS SELECT device_id, toStartOfFiveMinutes(timestamp) AS timestamp, avg(rtt_ms) AS avg_rtt_ms, min(min_rtt_ms) AS min_rtt_ms, max(max_rtt_ms) AS max_rtt_ms, avg(packet_loss) AS avg_packet_loss, avg(jitter_ms) AS avg_jitter_ms, avg(is_up) AS uptime_pct, count() AS sample_count, any(ip_address) AS ip_address FROM zenplus.ping_metrics GROUP BY device_id, toStartOfFiveMinutes(timestamp);

CREATE MATERIALIZED VIEW IF NOT EXISTS zenplus.ping_metrics_1h_mv TO zenplus.ping_metrics_1h AS SELECT device_id, toStartOfHour(timestamp) AS timestamp, avg(avg_rtt_ms) AS avg_rtt_ms, min(min_rtt_ms) AS min_rtt_ms, max(max_rtt_ms) AS max_rtt_ms, quantile(0.95)(avg_rtt_ms) AS p95_rtt_ms, avg(avg_packet_loss) AS avg_packet_loss, avg(avg_jitter_ms) AS avg_jitter_ms, avg(uptime_pct) AS uptime_pct, sum(sample_count) AS sample_count, any(ip_address) AS ip_address FROM zenplus.ping_metrics_5m GROUP BY device_id, toStartOfHour(timestamp);
