#!/bin/bash
# ============================================================================
# ZenPlus Security Setup
#
# Installs everything the Settings -> General -> Security tab needs:
#   - a root-owned copy of the privileged TLS helper in /usr/local/sbin
#   - the narrow sudoers policy that lets the zenplus service user run it
#   - /etc/zenplus/tls (certificate store) and the API-side staging directory
#
# Idempotent — safe to re-run, and run as a hook on every OTA update.
#   sudo bash scripts/setup-security.sh
# ============================================================================
set -e

ZENPLUS_DIR="${ZENPLUS_DIR:-/opt/zenplus}"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
log()  { echo -e "${GREEN}[setup-security]${NC} $1"; }
warn() { echo -e "${YELLOW}[setup-security]${NC} $1"; }

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must run as root (sudo bash scripts/setup-security.sh)" >&2
    exit 1
fi

# ── 1. Privileged helper script ─────────────────────────────────────────────
# The root-owned installed copy is the security boundary: /opt/zenplus/scripts
# is writable by the zenplus service account, so sudoers must never point at
# it directly.
if [ -f "${ZENPLUS_DIR}/scripts/zenplus-security-helper" ]; then
    install -o root -g root -m 0755 \
        "${ZENPLUS_DIR}/scripts/zenplus-security-helper" \
        /usr/local/sbin/zenplus-security-helper
    log "Installed /usr/local/sbin/zenplus-security-helper"
else
    warn "scripts/zenplus-security-helper not found — skipping helper install"
fi

# ── 2. Sudoers policy ───────────────────────────────────────────────────────
# One entry: the helper validates its own arguments and reads certificate
# material only from the fixed staging directory, so the grant stays narrow.
cat > /etc/sudoers.d/zenplus-security.tmp <<'SUDOEOF'
# Generated by ZenPlus setup-security.sh — do not edit by hand.
# TLS / web-security management for Settings -> General -> Security:
# certificate install, nginx HTTPS config generation and reload.
zenplus ALL=(root) NOPASSWD: /usr/local/sbin/zenplus-security-helper *
SUDOEOF
chmod 0440 /etc/sudoers.d/zenplus-security.tmp
# Validate before moving into place — a bad sudoers file breaks sudo entirely.
if visudo -cf /etc/sudoers.d/zenplus-security.tmp >/dev/null 2>&1; then
    mv /etc/sudoers.d/zenplus-security.tmp /etc/sudoers.d/zenplus-security
    log "Sudoers policy installed and validated"
else
    rm -f /etc/sudoers.d/zenplus-security.tmp
    warn "sudoers validation failed — security privileges NOT granted"
fi

# ── 3. Directories ──────────────────────────────────────────────────────────
# Certificate store (root-owned; the public cert is world-readable, the key
# is 0600 root). The staging dir is where the API, running as zenplus, places
# cert material for the helper to validate and install.
install -o root -g root -m 0755 -d /etc/zenplus /etc/zenplus/tls
install -o zenplus -g zenplus -m 0700 -d "${ZENPLUS_DIR}/data/tls-staging"
log "Certificate store and staging directories ready"

log "Security setup complete"
