#!/bin/bash
# ============================================================================
# ZenPlus Storage Management Setup
#
# Installs everything the Settings -> Storage tab needs:
#   - root-owned copies of the privileged helper scripts in /usr/local/sbin
#   - the narrow sudoers policy that lets the zenplus service user run them
#   - backup directories on the data volume
#   - the ClickHouse 'backups' disk config (bind-mounted into the container)
#
# Idempotent — safe to re-run, and run as a hook on every OTA update.
#   sudo bash scripts/setup-storage.sh
# ============================================================================
set -e

ZENPLUS_DIR="${ZENPLUS_DIR:-/opt/zenplus}"
DATA_MOUNT="/data"
CH_CONTAINER="zenplus-clickhouse"
CH_UID=101   # clickhouse user inside the official image
CH_NETWORK="zenplus_clickhouse"
LEGACY_CH_NETWORK="zenplus_default"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
log()  { echo -e "${GREEN}[setup-storage]${NC} $1"; }
warn() { echo -e "${YELLOW}[setup-storage]${NC} $1"; }

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must run as root (sudo bash scripts/setup-storage.sh)" >&2
    exit 1
fi

# ── 1. Privileged helper scripts ────────────────────────────────────────────
# Root-owned installed copies are the security boundary: /opt/zenplus/bin and
# /opt/zenplus/scripts are writable by the zenplus service account, so sudoers
# must never point at them directly.
if [ -f "${ZENPLUS_DIR}/scripts/zenplus-storage-helper" ]; then
    install -o root -g root -m 0755 \
        "${ZENPLUS_DIR}/scripts/zenplus-storage-helper" \
        /usr/local/sbin/zenplus-storage-helper
    log "Installed /usr/local/sbin/zenplus-storage-helper"
else
    warn "scripts/zenplus-storage-helper not found — skipping helper install"
fi

if [ -f "${ZENPLUS_DIR}/bin/expand-storage.sh" ]; then
    install -o root -g root -m 0755 \
        "${ZENPLUS_DIR}/bin/expand-storage.sh" \
        /usr/local/sbin/zenplus-expand-storage
    log "Installed /usr/local/sbin/zenplus-expand-storage"
else
    warn "bin/expand-storage.sh not found — disk expansion will be unavailable"
fi

# ── 2. Sudoers policy ───────────────────────────────────────────────────────
# Each entry corresponds to an exact subprocess call in
# server/app/api/v1/system_updates.py or services/storage_service.py.
# Keep these narrow; the helper scripts validate their own arguments.
install -o root -g root -m 0755 "${ZENPLUS_DIR}/scripts/zenplus-lvm-helper" /usr/local/sbin/zenplus-lvm-helper

cat > /etc/sudoers.d/zenplus-storage.tmp <<'SUDOEOF'
# Generated by ZenPlus setup-storage.sh — do not edit by hand.
# Storage management for Settings -> Storage: LVM introspection/expansion,
# component sizing, and privileged helper operations (SCSI rescan, pg
# dump/restore as postgres, journal vacuum, apt clean, service restarts).
zenplus ALL=(root) NOPASSWD: /usr/local/sbin/zenplus-lvm-helper vgs *
zenplus ALL=(root) NOPASSWD: /usr/local/sbin/zenplus-lvm-helper lvs *
zenplus ALL=(root) NOPASSWD: /usr/local/sbin/zenplus-lvm-helper pvs *
zenplus ALL=(root) NOPASSWD: /usr/local/sbin/zenplus-lvm-helper pvresize *
zenplus ALL=(root) NOPASSWD: /usr/bin/du -sb /data/clickhouse, /usr/bin/du -sb /data/postgresql, /usr/bin/du -sb /data/redis, /usr/bin/du -sb /data/backups, /usr/bin/du -sb /data/tmp
zenplus ALL=(root) NOPASSWD: /usr/local/sbin/zenplus-expand-storage *
zenplus ALL=(root) NOPASSWD: /usr/local/sbin/zenplus-storage-helper *
SUDOEOF
chmod 0440 /etc/sudoers.d/zenplus-storage.tmp
# Validate before moving into place — a bad sudoers file breaks sudo entirely.
if visudo -cf /etc/sudoers.d/zenplus-storage.tmp >/dev/null 2>&1; then
    mv /etc/sudoers.d/zenplus-storage.tmp /etc/sudoers.d/zenplus-storage
    log "Sudoers policy installed and validated"
else
    rm -f /etc/sudoers.d/zenplus-storage.tmp
    warn "sudoers validation failed — storage privileges NOT granted"
fi

# ── 3. Backup directories ───────────────────────────────────────────────────
# setgid on the appliance dir so files stay group-writable for the API user.
mkdir -p "${DATA_MOUNT}/backups/appliance" "${DATA_MOUNT}/backups/clickhouse"
chown zenplus:zenplus "${DATA_MOUNT}/backups/appliance" 2>/dev/null || true
chmod 2775 "${DATA_MOUNT}/backups/appliance"
chown "${CH_UID}:${CH_UID}" "${DATA_MOUNT}/backups/clickhouse" 2>/dev/null || true
log "Backup directories ready under ${DATA_MOUNT}/backups"

# ── 4. ClickHouse 'backups' disk ────────────────────────────────────────────
# docker-compose.yml bind-mounts docker/clickhouse/backup_disk.xml into the
# container's config.d. If that file were missing, Docker would create a
# DIRECTORY at the bind source and ClickHouse would fail to parse it — so
# never let the compose file reference a path that does not exist.
CH_CONF="${ZENPLUS_DIR}/docker/clickhouse/backup_disk.xml"
if [ ! -f "$CH_CONF" ]; then
    mkdir -p "$(dirname "$CH_CONF")"
    cat > "$CH_CONF" <<'XMLEOF'
<clickhouse>
    <storage_configuration>
        <disks>
            <backups>
                <type>local</type>
                <path>/backups/</path>
            </backups>
        </disks>
    </storage_configuration>
    <backups>
        <allowed_disk>backups</allowed_disk>
        <allowed_path>/backups/</allowed_path>
    </backups>
</clickhouse>
XMLEOF
    log "Restored missing ClickHouse backup-disk config"
fi

# Recreate the container when it is missing the backups mount or still uses
# the legacy default bridge. Giving the replacement network a stable name lets
# Compose create it before detaching ClickHouse from the old network.
if command -v docker >/dev/null 2>&1 && docker inspect "$CH_CONTAINER" >/dev/null 2>&1; then
    CH_NETWORKS="$(docker inspect -f '{{range $name, $network := .NetworkSettings.Networks}}{{$name}} {{end}}' "$CH_CONTAINER" 2>/dev/null || true)"
    CH_MOUNTS="$(docker inspect -f '{{range .Mounts}}{{.Destination}} {{end}}' "$CH_CONTAINER" 2>/dev/null || true)"
    if [[ " $CH_NETWORKS " == *" $CH_NETWORK "* && " $CH_MOUNTS " == *" /backups "* ]]; then
        log "ClickHouse network and backups disk are current"
    else
        log "Recreating ClickHouse with the current storage and network configuration ..."
        if (cd "$ZENPLUS_DIR" && docker compose up -d --force-recreate clickhouse >/dev/null 2>&1); then
            for _ in $(seq 1 24); do
                [ "$(docker inspect -f '{{.State.Health.Status}}' "$CH_CONTAINER" 2>/dev/null)" = "healthy" ] && break
                sleep 5
            done
            CH_HEALTH="$(docker inspect -f '{{.State.Health.Status}}' "$CH_CONTAINER" 2>/dev/null || true)"
            if [ "$CH_HEALTH" = "healthy" ]; then
                if [ "$LEGACY_CH_NETWORK" != "$CH_NETWORK" ] && docker network inspect "$LEGACY_CH_NETWORK" >/dev/null 2>&1; then
                    docker network rm "$LEGACY_CH_NETWORK" >/dev/null 2>&1 || \
                        warn "Legacy Docker network $LEGACY_CH_NETWORK is still in use"
                fi
                log "ClickHouse recreated (healthy)"
            else
                warn "ClickHouse did not become healthy after recreation (status: ${CH_HEALTH:-unknown})"
                exit 1
            fi
        else
            warn "Could not recreate ClickHouse with the current configuration"
            exit 1
        fi
    fi
fi

log "Storage management setup complete"
